import {
  Activity,
  AlertTriangle,
  AppWindow,
  Award,
  BarChart3,
  Bomb,
  Code2,
  Cpu,
  Eye,
  FileText,
  Flame,
  FolderGit2,
  Globe,
  Grid,
  Heading,
  ImageIcon,
  LayoutGrid,
  LayoutTemplate,
  Minus,
  Monitor,
  Music,
  Palette,
  PieChart,
  Quote,
  Radio,
  Share2,
  ShieldCheck,
  Sparkles,
  Terminal,
  TerminalSquare,
  TrendingUp,
  Trophy,
  Tv,
  Type,
  User,
  Video,
} from 'lucide-react'
import React from 'react'

import { WIDGET_CATEGORIES, WIDGET_IDS, WidgetCategory, WidgetId } from '@/constants'

export type WidgetBadgeType =
  'popular' | 'essential' | 'highlight' | 'interactive' | 'trending' | 'new'

export interface WidgetBadge {
  text: string
  type: WidgetBadgeType
}

export interface WidgetCatalogItem {
  id: WidgetId
  name: string
  desc?: string
  icon: React.ElementType
  isExternal?: boolean
  badge?: WidgetBadge
  category?: WidgetCategory
  defaultSize?: { width: number; height: number }
}

export interface WidgetFilterItem {
  id: string
  labelKey: string
  defaultLabel: string
  icon: React.ElementType
  match: (item: WidgetCatalogItem) => boolean
}

export const FEATURED_WIDGET_IDS = new Set<WidgetId>([
  WIDGET_IDS.GITFEST_LINEUP,
  WIDGET_IDS.POKEMON_CARD,
  WIDGET_IDS.GITFUT_CARD,
])

export const NATIVE_WIDGET_CATEGORIES = new Set<WidgetCategory>([
  WIDGET_CATEGORIES.ESSENTIAL,
  WIDGET_CATEGORIES.INTERACTIVE,
  WIDGET_CATEGORIES.STATS,
  WIDGET_CATEGORIES.MISC,
])

export const isFeaturedWidget = (item: Pick<WidgetCatalogItem, 'id'>): boolean =>
  FEATURED_WIDGET_IDS.has(item.id)

export const isNativeWidget = (
  item: Pick<WidgetCatalogItem, 'id' | 'category' | 'isExternal'>
): boolean =>
  !FEATURED_WIDGET_IDS.has(item.id) &&
  (item.category ? NATIVE_WIDGET_CATEGORIES.has(item.category) : !item.isExternal)

export const isExternalWidget = (item: Pick<WidgetCatalogItem, 'id' | 'category'>): boolean =>
  !FEATURED_WIDGET_IDS.has(item.id) && item.category === WIDGET_CATEGORIES.EXTERNAL

export const WIDGET_CATALOG: WidgetCatalogItem[] = [
  {
    id: WIDGET_IDS.HEADER,
    name: 'Header',
    icon: Heading,
    desc: 'Name, handle & company badge',
    category: WIDGET_CATEGORIES.ESSENTIAL,
    badge: { text: 'Mais Usado', type: 'popular' },
  },
  {
    id: WIDGET_IDS.ASCII_TEXT,
    name: 'ASCII Text',
    icon: Type,
    desc: 'Custom text rendered in ASCII art font',
    category: WIDGET_CATEGORIES.INTERACTIVE,
    badge: { text: 'Novo', type: 'highlight' },
  },
  {
    id: WIDGET_IDS.ASCII_ART,
    name: 'ASCII Art',
    icon: Terminal,
    desc: 'Image converted to character art',
    category: WIDGET_CATEGORIES.INTERACTIVE,
    badge: { text: 'Destaque', type: 'highlight' },
  },
  {
    id: WIDGET_IDS.TERMINAL_INFO,
    name: 'Terminal Info',
    icon: TerminalSquare,
    desc: 'Neofetch-style terminal info card',
    category: WIDGET_CATEGORIES.ESSENTIAL,
    badge: { text: 'Mais Usado', type: 'popular' },
  },
  {
    id: WIDGET_IDS.AVATAR,
    name: 'Avatar',
    icon: User,
    desc: 'Profile picture frame',
    category: WIDGET_CATEGORIES.ESSENTIAL,
    badge: { text: 'Essencial', type: 'essential' },
  },
  {
    id: WIDGET_IDS.TECH_STACK,
    name: 'Tech Stack',
    icon: Cpu,
    desc: 'Interactive skill icons gallery',
    category: WIDGET_CATEGORIES.INTERACTIVE,
    badge: { text: 'Interativo', type: 'interactive' },
  },
  {
    id: WIDGET_IDS.BIO,
    name: 'Bio & Links',
    icon: FileText,
    desc: 'Biography, location & blog link',
    category: WIDGET_CATEGORIES.ESSENTIAL,
  },
  {
    id: WIDGET_IDS.CUSTOM_IMAGE,
    name: 'Image',
    icon: FileText,
    desc: 'Custom image or banner',
    category: WIDGET_CATEGORIES.MISC,
  },
  {
    id: WIDGET_IDS.POKEMON_CARD,
    name: 'Pokémon Card',
    icon: Sparkles,
    category: WIDGET_CATEGORIES.INTERACTIVE,
    badge: { text: 'Novo', type: 'highlight' },
    defaultSize: { width: 300, height: 418 },
  },
  {
    id: WIDGET_IDS.GITFUT_CARD,
    name: 'GitFut Card',
    icon: Trophy,
    desc: 'GitHub profile rated out of 99 in FIFA FUT card style',
    category: WIDGET_CATEGORIES.INTERACTIVE,
    badge: { text: 'SCOUT 99', type: 'highlight' },
    defaultSize: { width: 300, height: 420 },
  },
  {
    id: WIDGET_IDS.STATS,
    name: 'GitHub Stats',
    icon: BarChart3,
    desc: 'Stars, repos, followers metrics',
    category: WIDGET_CATEGORIES.STATS,
    badge: { text: 'Popular', type: 'popular' },
  },
  {
    id: WIDGET_IDS.LANGUAGES,
    name: 'Top Languages',
    icon: Code2,
    desc: 'Language breakdown bar',
    category: WIDGET_CATEGORIES.STATS,
  },
  {
    id: WIDGET_IDS.REPOSITORIES,
    name: 'Featured Repos',
    icon: FolderGit2,
    desc: 'Highlighted repository cards',
    category: WIDGET_CATEGORIES.STATS,
  },
  {
    id: WIDGET_IDS.SOCIAL_MEDIA,
    name: 'Social Media',
    icon: Share2,
    desc: 'Shields & social media badges',
    category: WIDGET_CATEGORIES.MISC,
  },

  {
    id: WIDGET_IDS.GITHUB_README_STATS,
    name: 'GitHub Readme Stats',
    icon: BarChart3,
    desc: 'Estatísticas, top linguagens & repos fixados',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
    badge: { text: 'Popular', type: 'popular' },
  },
  {
    id: WIDGET_IDS.STREAK_STATS,
    name: 'GitHub Streak Stats',
    icon: Flame,
    desc: 'Sequência e recorde de contribuições',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
  },
  {
    id: WIDGET_IDS.PROFILE_TROPHY,
    name: 'GitHub Profile Trophy',
    icon: Trophy,
    desc: 'Troféus e conquistas do perfil',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
  },
  {
    id: WIDGET_IDS.ACTIVITY_GRAPH,
    name: 'Activity Graph',
    icon: Activity,
    desc: 'Gráfico de linhas de atividade em 31 dias',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
  },
  {
    id: WIDGET_IDS.CONTRIBUTION_SNAKE,
    name: 'Contribution Snake',
    icon: TrendingUp,
    desc: 'Cobra animada comendo os blocos de commit',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
    badge: { text: 'Trending', type: 'trending' },
  },
  {
    id: WIDGET_IDS.METRICS_CARD,
    name: 'Metrics Card',
    icon: PieChart,
    desc: 'Infográfico avançado de métricas e hábitos',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
  },
  {
    id: WIDGET_IDS.VIEWS_COUNTER,
    name: 'Profile Views Counter',
    icon: Eye,
    desc: 'Contador de visitas ao perfil GitHub',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
  },
  {
    id: WIDGET_IDS.README_QUOTES,
    name: 'GitHub Readme Quotes',
    icon: Quote,
    desc: 'Citação diária para desenvolvedores',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
  },
  {
    id: WIDGET_IDS.AWESOME_BADGE,
    name: 'Awesome Profile Badge',
    icon: Award,
    desc: 'Badge de destaque para perfis incríveis',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
  },
  {
    id: WIDGET_IDS.GITFEST_LINEUP,
    name: 'GitFest',
    icon: Sparkles,
    desc: 'Festival lineup of your repos',
    category: WIDGET_CATEGORIES.INTERACTIVE,
    badge: { text: 'New', type: 'highlight' },
  },

  {
    id: WIDGET_IDS.GHSTATS,
    name: 'GHStats.dev',
    icon: BarChart3,
    desc: 'GitHub Stats Cards from ghstats.dev',
    isExternal: true,
    category: WIDGET_CATEGORIES.EXTERNAL,
    badge: { text: 'New', type: 'highlight' },
  },
  {
    id: WIDGET_IDS.DIVIDER,
    name: 'Neon Divider',
    icon: Minus,
    desc: 'Section separator line',
    category: WIDGET_CATEGORIES.MISC,
  },
  {
    id: WIDGET_IDS.FOOTER,
    name: 'Footer Stamp',
    icon: LayoutTemplate,
    desc: 'Signature metadata footer',
    category: WIDGET_CATEGORIES.MISC,
  },
  {
    id: WIDGET_IDS.GODPROFILE_TERMINAL,
    name: 'Terminal Emulator',
    icon: TerminalSquare,
    desc: 'Animated typewriter terminal SVG',
    category: WIDGET_CATEGORIES.GODPROFILE,
    isExternal: true,
    defaultSize: { width: 450, height: 300 },
  },
  {
    id: WIDGET_IDS.GODPROFILE_MARQUEE,
    name: 'Icon Marquee',
    icon: Sparkles,
    desc: 'Infinite CSS-scrolling tech badges',
    category: WIDGET_CATEGORIES.GODPROFILE,
    isExternal: true,
    defaultSize: { width: 800, height: 120 },
  },
  {
    id: WIDGET_IDS.GODPROFILE_NEURAL,
    name: 'Neural Network Map',
    icon: Activity,
    desc: 'Animated tech stack visualization',
    category: WIDGET_CATEGORIES.GODPROFILE,
    isExternal: true,
    defaultSize: { width: 800, height: 320 },
  },
  {
    id: WIDGET_IDS.GODPROFILE_TROPHIES,
    name: 'GitHub Trophies',
    icon: Trophy,
    desc: 'Trophy case with S/A/B/C tiers',
    category: WIDGET_CATEGORIES.GODPROFILE,
    isExternal: true,
    defaultSize: { width: 800, height: 280 },
  },
  {
    id: WIDGET_IDS.GODPROFILE_WAKATIME,
    name: 'WakaTime Activity',
    icon: BarChart3,
    desc: 'Coding stats horizontal bar chart',
    category: WIDGET_CATEGORIES.GODPROFILE,
    isExternal: true,
    defaultSize: { width: 420, height: 260 },
  },

  {
    id: WIDGET_IDS.GODPROFILE_GLOBE,
    name: '3D Contribution Globe',
    icon: Globe,
    desc: 'Isometric 3D globe SVG',
    category: WIDGET_CATEGORIES.GODPROFILE,
    isExternal: true,
    defaultSize: { width: 320, height: 350 },
  },
  {
    id: WIDGET_IDS.ASCII_PORTRAIT,
    name: 'ASCII Portrait',
    icon: Terminal,
    desc: 'Animated monochrome typing ASCII portrait',
    category: WIDGET_CATEGORIES.ASCIIPROFILE,
    isExternal: true,
    defaultSize: { width: 370, height: 400 },
  },
  {
    id: WIDGET_IDS.ASCII_INFO,
    name: 'ASCII Info Card',
    icon: FileText,
    desc: 'Neofetch-style ASCII profile info card',
    category: WIDGET_CATEGORIES.ASCIIPROFILE,
    isExternal: true,
    defaultSize: { width: 490, height: 400 },
  },
  {
    id: WIDGET_IDS.ASCII_HEATMAP,
    name: 'ASCII Heatmap',
    icon: Grid,
    desc: 'Animated contribution heatmap calendar',
    category: WIDGET_CATEGORIES.ASCIIPROFILE,
    isExternal: true,
    defaultSize: { width: 780, height: 240 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_SYSTEM_LOOP,
    name: 'Control Plane Loop',
    icon: Cpu,
    desc: 'Animated closed-loop architecture map of repositories',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 360 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_COMMAND_DECK,
    name: 'Command Deck Console',
    icon: TerminalSquare,
    desc: 'Mission dashboard showing active deployment status & flagships',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 300 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_SIGNAL_GRID,
    name: 'Signal Grid Mesh',
    icon: Share2,
    desc: 'Wired signal topology map and connected grid structure',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 320 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_METRO,
    name: 'Metro Transit Map',
    icon: LayoutTemplate,
    desc: 'Repositories represented as a moving network of train lines',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 350 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_BENTO,
    name: 'Bento Grid Workbench',
    icon: Grid,
    desc: 'Modular grid displaying project metrics and components',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 340 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_EDITORIAL,
    name: 'Editorial Portfolio',
    icon: FileText,
    desc: 'Restrained, typographic selected work index and project archive',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_BLUEPRINT,
    name: 'Blueprint Assemblies',
    icon: FileText,
    desc: 'Engineering drawing assembly parts index blueprint layout',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_CONSTELLATION,
    name: 'Constellation Star Chart',
    icon: Globe,
    desc: 'Connected star chart constellation map of projects',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_MONOLITH,
    name: 'Monolith Strata Index',
    icon: Grid,
    desc: 'Stark internationalist poster strata index list layout',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_INTERLACE,
    name: 'Interlace Loom weave',
    icon: LayoutTemplate,
    desc: 'Quiet project loom thread archive weave layout',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_CIPHER,
    name: 'Cipher Print Rosette',
    icon: Sparkles,
    desc: 'Engraved rosette index and edition ledger register folio',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_SPECIMEN,
    name: 'Field Specimen Catalog',
    icon: FileText,
    desc: 'Exploratory dichotomous key and taxonomy specimen plate',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_PATCHBAY,
    name: 'Patch Bay Channels',
    icon: Share2,
    desc: 'Modular audio patch panel cable routing strip layout',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_CARTOGRAPH,
    name: 'Cartograph Contour survey',
    icon: Globe,
    desc: 'Contour topographic survey datums gazetteer map',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CONTROLPLANE_FOUNDRY,
    name: 'Foundry Casting yard',
    icon: Cpu,
    desc: 'Casting floor alloys smelted master mold ingot ledger',
    category: WIDGET_CATEGORIES.CONTROLPLANE,
    isExternal: true,
    defaultSize: { width: 800, height: 330 },
  },
  {
    id: WIDGET_IDS.CODEWEB_HERO_ORBIT,
    name: 'Aura Hero Orbit',
    icon: Sparkles,
    desc: 'Cosmic orbit banner with pulsating glowing orbs and radar concentric rings',
    category: WIDGET_CATEGORIES.CODEWEB_DEV,
    isExternal: true,
    badge: { text: 'Codeweb', type: 'highlight' },
    defaultSize: { width: 800, height: 360 },
  },
  {
    id: WIDGET_IDS.CODEWEB_SHOWCASE_CARDS,
    name: 'Aura Showcase Cards',
    icon: LayoutTemplate,
    desc: 'Aura dual card showcase with cosmic glow, animated Giphy GIF backgrounds, customizable Lucide icons and terminal prompt',
    category: WIDGET_CATEGORIES.CODEWEB_DEV,
    isExternal: true,
    badge: { text: 'Codeweb', type: 'highlight' },
    defaultSize: { width: 800, height: 220 },
  },
  {
    id: WIDGET_IDS.CODEWEB_RETRO_GRID,
    name: 'Aura Bento Cards',
    icon: LayoutGrid,
    desc: 'Modular glassmorphic bento identity showcase with stats chips and cover',
    category: WIDGET_CATEGORIES.CODEWEB_DEV,
    isExternal: true,
    badge: { text: 'Codeweb', type: 'new' },
    defaultSize: { width: 800, height: 260 },
  },
  {
    id: WIDGET_IDS.CODEWEB_SOCIAL_BADGE,
    name: 'Aura Social Badge',
    icon: Share2,
    desc: 'Glowing animated rotating gradient badges with strip and grid modes',
    category: WIDGET_CATEGORIES.CODEWEB_DEV,
    isExternal: true,
    badge: { text: 'Codeweb', type: 'popular' },
    defaultSize: { width: 800, height: 44 },
  },
  {
    id: WIDGET_IDS.CODEWEB_MINIMAL_BADGE,
    name: 'Aura Minimalist Banner',
    icon: Heading,
    desc: 'Sleek minimalist badge with precision tracking and typography accents',
    category: WIDGET_CATEGORIES.CODEWEB_DEV,
    isExternal: true,
    badge: { text: 'Codeweb', type: 'new' },
    defaultSize: { width: 800, height: 44 },
  },
  {
    id: WIDGET_IDS.SURVEILLANCE_HEADER,
    name: 'Surveillance Header',
    icon: Tv,
    desc: 'Retro 198X surveillance camera feed with chromatic jitter and boot log',
    category: WIDGET_CATEGORIES.SURVEILLANCE,
    isExternal: true,
    badge: { text: '198X', type: 'highlight' },
    defaultSize: { width: 780, height: 417 },
  },
  {
    id: WIDGET_IDS.SURVEILLANCE_DOSSIER,
    name: 'Subject Dossier',
    icon: User,
    desc: 'Classified subject profile dossier with rig, class, and status telemetry',
    category: WIDGET_CATEGORIES.SURVEILLANCE,
    isExternal: true,
    badge: { text: '198X', type: 'new' },
    defaultSize: { width: 780, height: 260 },
  },
  {
    id: WIDGET_IDS.SURVEILLANCE_LOADOUT,
    name: 'Daily Loadout',
    icon: Cpu,
    desc: 'Tactical workflow and programming language chip matrix',
    category: WIDGET_CATEGORIES.SURVEILLANCE,
    isExternal: true,
    badge: { text: '198X', type: 'popular' },
    defaultSize: { width: 780, height: 200 },
  },
  {
    id: WIDGET_IDS.SURVEILLANCE_TELEMETRY,
    name: 'Terminal Telemetry',
    icon: TerminalSquare,
    desc: 'Core metrics, colorblind language bar and 2D contribution heatmap',
    category: WIDGET_CATEGORIES.SURVEILLANCE,
    isExternal: true,
    badge: { text: '198X', type: 'trending' },
    defaultSize: { width: 780, height: 420 },
  },
  {
    id: WIDGET_IDS.SURVEILLANCE_TRANSMISSION,
    name: 'Incoming Transmission',
    icon: Radio,
    desc: 'Encrypted incoming transmission log with developer quotation',
    category: WIDGET_CATEGORIES.SURVEILLANCE,
    isExternal: true,
    badge: { text: '198X', type: 'new' },
    defaultSize: { width: 780, height: 160 },
  },
  {
    id: WIDGET_IDS.SURVEILLANCE_FIELD,
    name: 'Field Recording VHS',
    icon: Video,
    desc: 'CRT multi-pane system monitor with VHS scanlines and rolling tracking line',
    category: WIDGET_CATEGORIES.SURVEILLANCE,
    isExternal: true,
    badge: { text: '198X', type: 'highlight' },
    defaultSize: { width: 780, height: 438 },
  },
  {
    id: WIDGET_IDS.SURVEILLANCE_FEEDS,
    name: 'Surveillance Social Feeds',
    icon: Share2,
    desc: 'Animated surveillance CCTV feeds for LinkedIn, Email, Discord and socials',
    category: WIDGET_CATEGORIES.SURVEILLANCE,
    isExternal: true,
    badge: { text: '198X', type: 'popular' },
    defaultSize: { width: 780, height: 190 },
  },
  {
    id: WIDGET_IDS.SURVEILLANCE_TITLE,
    name: 'Surveillance Section Title',
    icon: Heading,
    desc: 'Compact surveillance section title bar with blinking LED status and reference tag',
    category: WIDGET_CATEGORIES.SURVEILLANCE,
    isExternal: true,
    badge: { text: '198X', type: 'new' },
    defaultSize: { width: 780, height: 30 },
  },
  {
    id: WIDGET_IDS.PREMIUM_ASCII_PROFILE_CARD,
    name: 'Profile Terminal Card',
    icon: Terminal,
    desc: 'All-in-one terminal card with GitHub metrics, roles, top repos, languages & prompt',
    category: WIDGET_CATEGORIES.PREMIUM_ASCII,
    isExternal: true,
    badge: { text: 'Master Card', type: 'highlight' },
    defaultSize: { width: 520, height: 440 },
  },
  {
    id: WIDGET_IDS.PREMIUM_ASCII_DEV_SCORE,
    name: 'Scorecard',
    icon: Award,
    desc: 'Synthetic score radar (Activity, Open Source, Consistency, Impact, Growth)',
    category: WIDGET_CATEGORIES.PREMIUM_ASCII,
    isExternal: true,
    badge: { text: 'Score 100', type: 'new' },
    defaultSize: { width: 400, height: 250 },
  },
  {
    id: WIDGET_IDS.PREMIUM_ASCII_INSIGHTS,
    name: 'Insights & Habits',
    icon: Sparkles,
    desc: 'Derived behavioral insights, peak times, and temporal productivity distribution',
    category: WIDGET_CATEGORIES.PREMIUM_ASCII,
    isExternal: true,
    badge: { text: 'Insights', type: 'popular' },
    defaultSize: { width: 400, height: 280 },
  },
  {
    id: WIDGET_IDS.PREMIUM_ASCII_DNA,
    name: 'DNA',
    icon: Cpu,
    desc: 'Behavioral traits breakdown (Builder, Maintainer, Open Source) and primary archetype',
    category: WIDGET_CATEGORIES.PREMIUM_ASCII,
    isExternal: true,
    badge: { text: 'DNA', type: 'new' },
    defaultSize: { width: 400, height: 230 },
  },
  {
    id: WIDGET_IDS.PREMIUM_ASCII_CODING_VELOCITY,
    name: 'Coding Velocity',
    icon: TrendingUp,
    desc: 'Monthly coding throughput metrics (Commits/mo, PRs/mo, Issues/mo, Avg. commits/day)',
    category: WIDGET_CATEGORIES.PREMIUM_ASCII,
    isExternal: true,
    badge: { text: 'Velocity', type: 'popular' },
    defaultSize: { width: 400, height: 160 },
  },
  {
    id: WIDGET_IDS.WINXP_WINDOW,
    name: 'XP Window Explorer',
    icon: AppWindow,
    desc: 'Classic Windows XP Luna explorer window with system specs, profile bio, and storage drive',
    category: WIDGET_CATEGORIES.WINDOWS_XP,
    isExternal: true,
    badge: { text: 'XP Luna', type: 'highlight' },
    defaultSize: { width: 780, height: 380 },
  },
  {
    id: WIDGET_IDS.WINXP_MINESWEEPER,
    name: 'XP Minesweeper Game',
    icon: Bomb,
    desc: 'Nostalgic Campo Minado / Minesweeper board reflecting commit activity score and timer',
    category: WIDGET_CATEGORIES.WINDOWS_XP,
    isExternal: true,
    badge: { text: 'Retro Game', type: 'new' },
    defaultSize: { width: 780, height: 340 },
  },
  {
    id: WIDGET_IDS.WINXP_MEDIA_PLAYER,
    name: 'Windows Media Player 9',
    icon: Music,
    desc: 'Iconic WMP skin with visualizer spectrum bars, now playing playlist, and equalizer controls',
    category: WIDGET_CATEGORIES.WINDOWS_XP,
    isExternal: true,
    badge: { text: 'Media 9', type: 'popular' },
    defaultSize: { width: 780, height: 300 },
  },
  {
    id: WIDGET_IDS.WINXP_PAINT,
    name: 'XP MS Paint Canvas',
    icon: Palette,
    desc: 'Retro Microsoft Paint application window with classic toolbar palette and live repo canvas',
    category: WIDGET_CATEGORIES.WINDOWS_XP,
    isExternal: true,
    badge: { text: 'MS Paint', type: 'new' },
    defaultSize: { width: 780, height: 360 },
  },
  {
    id: WIDGET_IDS.WINXP_TASKBAR,
    name: 'XP Start Taskbar',
    icon: LayoutTemplate,
    desc: 'Green Start button, active system tray with notification icons, and quick-launch social items',
    category: WIDGET_CATEGORIES.WINDOWS_XP,
    isExternal: true,
    badge: { text: 'Start Bar', type: 'popular' },
    defaultSize: { width: 780, height: 48 },
  },
  {
    id: WIDGET_IDS.WINXP_ERROR_DIALOG,
    name: 'XP Critical Error Dialog',
    icon: AlertTriangle,
    desc: 'Famous Windows XP Critical Stop error modal dialog with customizable alert message and code',
    category: WIDGET_CATEGORIES.WINDOWS_XP,
    isExternal: true,
    badge: { text: '0x000000', type: 'highlight' },
    defaultSize: { width: 520, height: 210 },
  },
  {
    id: WIDGET_IDS.WINXP_SYSTEM_PROPERTIES,
    name: 'XP System Properties (Languages)',
    icon: Monitor,
    desc: 'Windows XP System Properties window showcasing top languages, byte metrics, and visual mode',
    category: WIDGET_CATEGORIES.WINDOWS_XP,
    isExternal: true,
    badge: { text: 'Languages', type: 'new' },
    defaultSize: { width: 780, height: 400 },
  },
  {
    id: WIDGET_IDS.WINXP_BLISS,
    name: 'Bliss Wallpaper',
    icon: ImageIcon,
    desc: 'Classic Windows XP Bliss wallpaper — the iconic green hill and blue sky, faithfully recreated in SVG',
    category: WIDGET_CATEGORIES.WINDOWS_XP,
    isExternal: true,
    defaultSize: { width: 780, height: 440 },
  },
]

export const WIDGET_FILTERS: WidgetFilterItem[] = [
  {
    id: 'all',
    labelKey: 'editor.sidebar.filter.all',
    defaultLabel: 'Todos',
    icon: Grid,
    match: () => true,
  },
  {
    id: 'popular',
    labelKey: 'editor.sidebar.filter.popular',
    defaultLabel: 'Destaques',
    icon: Flame,
    match: (item) =>
      item.badge?.type === 'popular' ||
      item.badge?.type === 'highlight' ||
      item.badge?.type === 'trending',
  },
  {
    id: 'essential',
    labelKey: 'editor.sidebar.filter.essential',
    defaultLabel: 'Essenciais',
    icon: ShieldCheck,
    match: (item) =>
      item.category === WIDGET_CATEGORIES.ESSENTIAL || item.badge?.type === 'essential',
  },
  {
    id: 'windows-xp',
    labelKey: 'editor.sidebar.filter.winxp',
    defaultLabel: 'Windows XP',
    icon: AppWindow,
    match: (item) => item.category === WIDGET_CATEGORIES.WINDOWS_XP,
  },
  {
    id: 'premiumascii',
    labelKey: 'editor.sidebar.filter.premiumascii',
    defaultLabel: 'ASCII Premium Kit',
    icon: Terminal,
    match: (item) => item.category === WIDGET_CATEGORIES.PREMIUM_ASCII,
  },
  {
    id: 'external',
    labelKey: 'editor.sidebar.filter.external',
    defaultLabel: 'Externos',
    icon: Globe,
    match: (item) => isExternalWidget(item),
  },
  {
    id: 'surveillance',
    labelKey: 'editor.sidebar.filter.surveillance',
    defaultLabel: 'Surveillance',
    icon: Radio,
    match: (item) => item.category === WIDGET_CATEGORIES.SURVEILLANCE,
  },
  {
    id: 'codeweb-dev',
    labelKey: 'editor.sidebar.filter.codeweb',
    defaultLabel: 'Codeweb-dev',
    icon: Sparkles,
    match: (item) => item.category === WIDGET_CATEGORIES.CODEWEB_DEV,
  },
  {
    id: 'godprofile',
    labelKey: 'editor.sidebar.filter.godprofile',
    defaultLabel: 'GodProfile',
    icon: Sparkles,
    match: (item) => item.category === WIDGET_CATEGORIES.GODPROFILE,
  },
  {
    id: 'asciiprofile',
    labelKey: 'editor.sidebar.filter.asciiprofile',
    defaultLabel: 'ASCII Profile',
    icon: TerminalSquare,
    match: (item) => item.category === WIDGET_CATEGORIES.ASCIIPROFILE,
  },
  {
    id: 'controlplane',
    labelKey: 'editor.sidebar.filter.controlplane',
    defaultLabel: 'Control Plane',
    icon: Cpu,
    match: (item) => item.category === WIDGET_CATEGORIES.CONTROLPLANE,
  },
]
